# Generated by Django 5.2.15 on 2026-07-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0007_userprofile_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='custom_permissions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='from_role',
            field=models.CharField(blank=True, choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('manager', 'Manager'), ('sme', 'SME'), ('mentor', 'Mentor'), ('staff', 'Staff (Intern View)'), ('intern', 'Intern')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='to_role',
            field=models.CharField(blank=True, choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('manager', 'Manager'), ('sme', 'SME'), ('mentor', 'Mentor'), ('staff', 'Staff (Intern View)'), ('intern', 'Intern')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('manager', 'Manager'), ('sme', 'SME'), ('mentor', 'Mentor'), ('staff', 'Staff (Intern View)'), ('intern', 'Intern')], default='intern', max_length=20),
        ),
    ]
